### ISSUE TITLE
Could not create a new chat? 

### ISSUE THREAD

**Issue by KnightCoder248** [Xtr4F/PyCharacterAI#1]
This repository may seem old but I'm currently working on to integrate this api onto a discord bot somehow. I'm also using replit.com as the platform for it to run. Here's the error log: 

Traceback (most recent call last):
  File "/home/runner/PyCharacterAI-1/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/runner/PyCharacterAI-1/main.py", line 45, in on_ready
    await setup_character_ai()
  File "/home/runner/PyCharacterAI-1/main.py", line 40, in setup_character_ai
    chat_session = await client.create_or_continue_chat(character_id)
  File "/home/runner/PyCharacterAI-1/PyCharacterAI/client.py", line 285, in create_or_continue_chat
    raise Exception('Could not create a new chat.')
Exception: Could not create a new chat.

**Comment by Xtr4F** [comment]
Hi. At the time this issue was created, the library was very outdated. A lot of things have changed in the api over the last year, so I've released a new version 2.0 that fixes many bugs and includes many new features, but unfortunately breaks backwards compatibility. If you are still interested in this project, you can check out the new version and read the documentation.

**Comment by azim218** [comment]
> Hi. At the time this issue was created, the library was very outdated. A lot of things have changed in the api over the last year, so I've released a new version 2.0 that fixes many bugs and includes many new features, but unfortunately breaks backwards compatibility. If you are still interested in this project, you can check out the new version and read the documentation.

wheres the 2.0 version kid

**Comment by Xtr4F** [comment]
@azim218 Hmm, I can't even guess...
![IMG_20241223_064006_969](https://github.com/user-attachments/assets/4260f71d-ed69-4977-98e4-0b149b7d1bee)
