### ISSUE TITLE
Existing chats?

### ISSUE THREAD

**Issue by wolfboss356** [Xtr4F/PyCharacterAI#14]
First of all, this is an amazing project. Not only did it work, but I now know how to find tokens on the new website. However, I was wondering if there was a way to access existing chats on your account, and continue talking to them rather than starting a new chat every time I run the script.

**Comment by Xtr4F** [comment]
Sure.

```Python
# get a list of all your chats with the character
chats = client.chat.fetch_chats("character_id")
```

If you are interested in your recent chats with characters, you can use this method:

```Python
# get a list of your recent chats
chats = await client.chat.fetch_recent_chats()
```

Also, if you want to either create a new chat with character or continue an existing one, you can use something like:

```Python
async def create_or_continue(character_id):
    chats = await client.chat.fetch_chats(character_id)
    if chats:
        return chats[0]
    
    chat, _ = await client.chat.create_chat(character_id)
    return chat
```

**Comment by wolfboss356** [comment]
Thanks! It worked. I wanted to note that chats[0] isn’t necessarily your most recent chat. Each chat is assigned a value that (in my experience) isn’t related to anything. In my case, my most recent chat ended up being 6.
