### ISSUE TITLE
holly shit 

### ISSUE THREAD

**Issue by azim218** [Xtr4F/PyCharacterAI#18]
ERROR: Object of type Chat is not JSON serializable
wtf

**Comment by Xtr4F** [comment]
Ну обнови ты уже библиотеку, пожалуйста 🙏

**Comment by Xtr4F** [comment]
Что ты вообще пытаешься сделать? Покажи пример кода

**Comment by azim218** [comment]
> Ну обнови ты уже библиотеку, пожалуйста 🙏

bro`s english died 🪑

**Comment by azim218** [comment]
> Что ты вообще пытаешься сделать? Покажи пример кода



> Что ты вообще пытаешься сделать? Покажи пример кода

def save_chat_data(self, history_id):
        """Сохранение данных чата."""
        try:
            with open("chat_data.pkl", "wb") as f:
                pickle.dump({"history_id": history_id}, f)
            print("Данные чата успешно сохранены.")
        except Exception as e:
            print(f"Ошибка при сохранении данных: {e}")

    def load_chat_data(self):
        """Загрузка данных чата."""
        if not os.path.exists("chat_data.pkl"):
            return None
        try:
            with open("chat_data.pkl", "rb") as f:
                chat_data = pickle.load(f)
            print("Данные чата успешно загружены.")
            return chat_data
        except Exception as e:
            print(f"Ошибка при загрузке данных: {e}")
            return None
            
fuck you

**Comment by Xtr4F** [comment]
https://github.com/user-attachments/assets/557ac522-ccb5-4216-bc30-14d03b2abbc9


Фу, грубиян какой-то, сам разруливай.
