### ISSUE TITLE
error when sending message for too long

### ISSUE THREAD

**Issue by GDjkhp** [Xtr4F/PyCharacterAI#8]
steps to reproduce:

1. send a message
2. wait
3. send another message <--

![image](https://github.com/user-attachments/assets/20747507-6bf9-4ec1-9b41-9d3d3c823df8)

**Comment by GDjkhp** [comment]
nvm i think i was fixed

**Comment by Xtr4F** [comment]
you're using a version of the library that uses an older version of websocket handling, which had a lot of bugs like this. Please consider updating to the latest version
